# Generated by Django 3.0.5 on 2020-04-21 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeID', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('Quantity', models.CharField(max_length=100)),
                ('ShortDesc', models.CharField(max_length=100)),
                ('LongDesc', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('stock', models.FloatField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dappx.productcategories')),
            ],
        ),
    ]
