# Generated by Django 3.0.5 on 2020-04-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_auto_20200421_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userType',
        ),
    ]
