# Generated by Django 3.0.5 on 2020-05-07 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0004_delete_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartTable',
            fields=[
                ('cartID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('totalCost', models.FloatField(max_length=100)),
                ('shipName', models.CharField(max_length=100)),
                ('shipAddress', models.CharField(max_length=100)),
                ('billingAddress', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('OnShipping', 'OnShipping'), ('Completed', 'Completed')], default='New')),
            ],
        ),
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dappx.cartTable')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dappx.products')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
