# Generated by Django 3.0.6 on 2020-05-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0007_auto_20200512_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email',
        ),
    ]
