# Generated by Django 3.0.6 on 2020-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0008_remove_userprofileinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
