# Generated by Django 3.0.5 on 2020-05-26 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0009_userprofileinfo_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cartID',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='username',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='billingAddress',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='shipAddress',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='shipName',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='totalCost',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='zip',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='itemID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='itemPrice',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='itemquantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dappx.products'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='totalCost',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dappx.cartItem'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('OnShipping', 'OnShipping'), ('Completed', 'Completed')], default='New', max_length=160),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='cartTable',
        ),
    ]
