# Generated by Django 3.0.6 on 2020-05-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0010_auto_20200526_1149'),
        ('dappx', '0010_auto_20200524_1747'),
    ]

    operations = [
    ]
