# Generated by Django 3.0.6 on 2020-05-27 18:15

import dappx.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0011_merge_20200526_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='date_due',
            field=models.DateTimeField(default=dappx.models.orders.return_date_due),
        ),
    ]
